// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import { application } from "./application"

import FilterBooksController from "./filter_books_controller"
application.register("filter-books", FilterBooksController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SearchBooksController from "./search_books_controller"
application.register("search-books", SearchBooksController)

// import Flatpickr
import Flatpickr from "stimulus-flatpickr"
application.register('flatpickr', Flatpickr)
