// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SearchBooksController from "./search_books_controller"
application.register("search-books", SearchBooksController)

import { Application } from '@hotwired/stimulus'
import ReadMore from 'stimulus-read-more'

const application = Application.start()
application.register('read-more', ReadMore)
